"""Claude tool-use schemas for the Trip mission.

The trip mission is interactive (multi-turn chat). Each turn of the agent
loop sees ONLY the tools allowed by the current phase — see
`trip_tools_for_phase` at the bottom of this file.
"""

from __future__ import annotations

from typing import Any


_TRIP_TOOLS: list[dict[str, Any]] = [
    # ─── UNDERSTAND-phase tools ────────────────────────────────────────
    {
        "name": "search_trip_options",
        "description": (
            "Run a LIVE, VISIBLE web search via DuckDuckGo. Chromium opens on the "
            "user's screen, the query is typed character-by-character, and real "
            "search results scroll in inside a stylized 'TripLens' search engine. "
            "ALSO emits the found links to a Research feed on the dashboard so the "
            "user can see what informed your picks. Fire 2-3 times with DIFFERENT, "
            "SPECIFIC queries (e.g. 'boutique hotel Cairo Nile', 'romantic dinner "
            "Cairo', 'Cairo activities Pyramids'). Returns "
            "{query, results: [{title, url, snippet}]}."
        ),
        "input_schema": {
            "type": "object",
            "required": ["query"],
            "properties": {
                "query":       {"type": "string", "description": "Specific search query: destination + category."},
                "max_results": {"type": "integer", "minimum": 3, "maximum": 8},
            },
        },
    },
    {
        "name": "present_options",
        "description": (
            "Render exactly 3 trip-package option cards in the chat panel. Each card "
            "gets a CARTOON ILLUSTRATION auto-generated by Seedream 4.5 from the option's "
            "hotel + restaurant + extra fields (no extra work for you). Each option MUST "
            "include a `sources` array citing the EXACT URLs from search_trip_options "
            "that informed it. Call this exactly once per mission, after research."
        ),
        "input_schema": {
            "type": "object",
            "required": ["intro_text", "options"],
            "properties": {
                "intro_text": {"type": "string", "description": "One short markdown sentence introducing the picks. May embed [links]() to top sources."},
                "options": {
                    "type": "array", "minItems": 3, "maxItems": 3,
                    "items": {
                        "type": "object",
                        "required": ["id", "hotel", "restaurant", "extra", "total_eur", "notes", "sources"],
                        "properties": {
                            "id":          {"type": "string", "description": "Short id like 'opt-a' / 'opt-b' / 'opt-c'"},
                            "hotel":       {"type": "string"},
                            "restaurant":  {"type": "string"},
                            "extra":       {"type": "string", "description": "One activity / experience"},
                            "total_eur":   {"type": "number"},
                            "notes":       {"type": "string", "description": "1-sentence vibe note"},
                            "sources": {
                                "type": "array", "minItems": 2, "maxItems": 5,
                                "items": {
                                    "type": "object",
                                    "required": ["label", "url"],
                                    "properties": {
                                        "label": {"type": "string", "description": "Short label, e.g. 'tripadvisor.com'"},
                                        "url":   {"type": "string"},
                                    },
                                },
                            },
                        },
                    },
                },
            },
        },
    },
    {
        "name": "request_confirmation",
        "description": (
            "Ask the user to confirm the selected plan before any money moves. Call "
            "this AFTER the user has picked an option. The user replies 'yes' / 'go' / "
            "'do it' to proceed. Include the total EUR + a one-line action summary."
        ),
        "input_schema": {
            "type": "object",
            "required": ["summary"],
            "properties": {
                "summary": {"type": "string", "description": "One-line plan summary + total EUR."},
            },
        },
    },

    # ─── EXECUTE-phase tools ───────────────────────────────────────────
    {
        "name": "create_sub_account",
        "description": (
            "Create a bunq savings sub-account with a goal amount, named after the trip. "
            "Returns {account_id, iban} which fund_sub_account uses automatically."
        ),
        "input_schema": {
            "type": "object",
            "required": ["name", "goal_eur"],
            "properties": {
                "name":     {"type": "string", "description": "Display name, e.g. '🇪🇬 Cairo Weekend'"},
                "goal_eur": {"type": "number", "description": "Goal amount in euros"},
            },
        },
    },
    {
        "name": "fund_sub_account",
        "description": (
            "Move EUR from primary into the trip sub-account. Self-heals primary balance "
            "via sandbox sugardaddy if short. The destination IBAN is picked up "
            "automatically from the most recent create_sub_account call."
        ),
        "input_schema": {
            "type": "object",
            "required": ["amount_eur"],
            "properties": {
                "amount_eur": {"type": "number"},
            },
        },
    },
    {
        "name": "book_hotel",
        "description": (
            "Have a real browser-agent (Playwright + Claude Vision) navigate the local "
            "mock hotel-booking site and complete a real reservation. Returns the actual "
            "confirmed hotel name, total EUR, nights, and reference. Use BEFORE pay_vendor."
        ),
        "input_schema": {
            "type": "object",
            "required": ["city", "nights", "max_budget_eur"],
            "properties": {
                "city":           {"type": "string"},
                "nights":         {"type": "integer", "minimum": 1, "maximum": 14},
                "max_budget_eur": {"type": "number"},
            },
        },
    },
    {
        "name": "pay_vendor",
        "description": (
            "Send an immediate payment from the user's primary account to a vendor. "
            "Use this for the hotel right after book_hotel returns — pay the EXACT "
            "price to the EXACT hotel_name."
        ),
        "input_schema": {
            "type": "object",
            "required": ["amount_eur", "vendor_name", "description"],
            "properties": {
                "amount_eur":    {"type": "number"},
                "vendor_name":   {"type": "string"},
                "description":   {"type": "string"},
                "vendor_email":  {"type": "string", "description": "Defaults to sandbox sugardaddy@bunq.com if omitted."},
            },
        },
    },
    {
        "name": "create_draft_payment",
        "description": (
            "Create a PENDING payment that requires the user to tap 'approve' in their bunq app. "
            "Use for the restaurant — the user's phone buzzes."
        ),
        "input_schema": {
            "type": "object",
            "required": ["amount_eur", "vendor_name", "description"],
            "properties": {
                "amount_eur":   {"type": "number"},
                "vendor_name":  {"type": "string"},
                "description":  {"type": "string"},
                "vendor_email": {"type": "string"},
            },
        },
    },
    {
        "name": "schedule_recurring_payment",
        "description": (
            "Schedule a weekly / monthly recurring payment from primary. Use for the "
            "future-trips savings deposit (e.g. €50/week into a 'Trip fund' counterparty)."
        ),
        "input_schema": {
            "type": "object",
            "required": ["amount_eur", "description", "recurrence_unit", "counterparty_name"],
            "properties": {
                "amount_eur":         {"type": "number"},
                "description":        {"type": "string"},
                "recurrence_unit":    {"type": "string", "enum": ["DAILY", "WEEKLY", "MONTHLY"]},
                "recurrence_size":    {"type": "integer", "minimum": 1},
                "days_from_now":      {"type": "integer", "minimum": 0},
                "counterparty_email": {"type": "string"},
                "counterparty_name":  {"type": "string"},
            },
        },
    },
    {
        "name": "request_money",
        "description": (
            "Ask someone to pay you via bunq request-inquiry. Use to split the trip cost "
            "with the partner. Counterparty email in sandbox should usually be sugardaddy@bunq.com "
            "(auto-accepts)."
        ),
        "input_schema": {
            "type": "object",
            "required": ["counterparty_email", "amount_eur", "description"],
            "properties": {
                "counterparty_email": {"type": "string"},
                "amount_eur":         {"type": "number"},
                "description":        {"type": "string"},
                "counterparty_name":  {"type": "string"},
            },
        },
    },
    {
        "name": "send_slack_message",
        "description": (
            "Send a Slack DM/channel message via the configured incoming webhook. "
            "Use to notify the partner during a trip mission ('Friday. Don't plan. Trust me.'). "
            "Keep messages short — they read like a real text. Use the optional `header` for a bold title."
        ),
        "input_schema": {
            "type": "object",
            "required": ["message"],
            "properties": {
                "message": {"type": "string"},
                "header":  {"type": "string", "description": "Short bold title rendered above the message."},
            },
        },
    },
    {
        "name": "narrate",
        "description": (
            "Speak a one-line summary to the user via TTS. Use AT MOST once per step so the demo "
            "feels narrated, not chatty. Keep each narration under 18 words, conversational, "
            "present tense."
        ),
        "input_schema": {
            "type": "object",
            "required": ["text"],
            "properties": {
                "text": {"type": "string"},
            },
        },
    },
    {
        "name": "finish_mission",
        "description": (
            "Signal the mission is complete. Include a final summary line for the user. "
            "After this, no more tool calls will be made."
        ),
        "input_schema": {
            "type": "object",
            "required": ["summary"],
            "properties": {
                "summary": {"type": "string"},
            },
        },
    },
]


def trip_tools_for_phase(phase: str) -> list[dict[str, Any]]:
    """Return the tool list to expose for a given trip-mission phase.

    Phases: UNDERSTANDING | AWAITING_CONFIRMATION | EXECUTING | DONE.
    The model literally can't see execute tools during UNDERSTAND, etc.
    """
    by_name = {t["name"]: t for t in _TRIP_TOOLS}

    if phase == "UNDERSTANDING":
        return [
            by_name["search_trip_options"],
            by_name["present_options"],
            by_name["request_confirmation"],
        ]
    if phase == "AWAITING_CONFIRMATION":
        return [by_name["request_confirmation"]]
    if phase == "EXECUTING":
        return [
            by_name["create_sub_account"],
            by_name["fund_sub_account"],
            by_name["book_hotel"],
            by_name["pay_vendor"],
            by_name["create_draft_payment"],
            by_name["schedule_recurring_payment"],
            by_name["request_money"],
            by_name["send_slack_message"],
            by_name["narrate"],
            by_name["finish_mission"],
        ]
    return []  # DONE
